### ISSUE TITLE
Crie um arquivo reset.css

### ISSUE THREAD

**Issue by devzone1001** [tmorais08/teste#1]
# Crie um arquivo reset.css

### Sugiro que adicione um arquivo de normalização de browsers 'reset.css'

![image](https://github.com/tmorais08/teste/assets/159345688/8ee101a9-af98-4e4e-9939-7721d30b4927)

**Comment by tmorais08** [comment]
Olá, obrigado pelo seu apontamento. Estarei adicionando o arquivo reset.css
